name: Extract and Translate HTML (Batch Interactive Base)

on:
  workflow_dispatch:
  push:
    paths:
      - 'uploaded_files/**/*.html'

jobs:
  extract_translate_batch_interactive:
    runs-on: ubuntu-latest

    env:
      DEEPL_AUTH_KEY: ${{ secrets.DEEPL_AUTH_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install spacy bs4 regex pypinyin deepl html5lib

      - name: Download spaCy models
        run: |
          python -m spacy download en_core_web_sm
          python -m spacy download fr_core_news_sm
          python -m spacy download zh_core_web_sm
          python -m spacy download xx_ent_wiki_sm

      - name: Run Interactive Batch Manager (Non-Prompt Mode)
        run: |
          python batch_manager.py --lang en --primary-lang en

      - name: Upload translated outputs
        uses: actions/upload-artifact@v4
        with:
          name: translated-results
          path: |
            translations.json
            translatable_flat.json
            translatable_structured.json
            translatable_flat_sentences.json
            processed_files/